### ISSUE TITLE
Ubuntu 18.04 closing after start

### ISSUE THREAD

**Issue by FilatovRA** [DragonComputer/Dragonfire#116]
dragonfire 
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/deepconv/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/deepconv/model-pretrainedv2/model.ckpt
________________________________________________________________________________

Dragonfire: GOOD MORNING SIR
________________________________________________________________________________

2019-04-22 11:57:19,457 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-04-22 11:57:19,458 INFO sqlalchemy.engine.base.Engine ()
2019-04-22 11:57:19,459 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-04-22 11:57:19,459 INFO sqlalchemy.engine.base.Engine ()
2019-04-22 11:57:19,460 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("users")
2019-04-22 11:57:19,460 INFO sqlalchemy.engine.base.Engine ()
2019-04-22 11:57:19,461 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("facts")
2019-04-22 11:57:19,461 INFO sqlalchemy.engine.base.Engine ()
2019-04-22 11:57:19,461 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("notifications")
2019-04-22 11:57:19,461 INFO sqlalchemy.engine.base.Engine ()
2019-04-22 11:57:19,462 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("notepad")
2019-04-22 11:57:19,462 INFO sqlalchemy.engine.base.Engine ()
Недопустимая инструкция (стек памяти сброшен на диск)

In english last line  means: "bad instruction"

**Comment by FilatovRA** [comment]
Using latest release https://github.com/DragonComputer/Dragonfire/releases/tag/v1.0.2

**Comment by FilatovRA** [comment]
Same issue I found in comment from vladislavyuzbekov here https://github.com/DragonComputer/Dragonfire/issues/110

**Comment by mertyildiran** [comment]
@FilatovRA could you provide me the original error message in English? Seems like an issue related to `sqlalchemy` but I'm not sure what's the reason.

**Comment by FilatovRA** [comment]
> @FilatovRA could you provide me the original error message in English? Seems like an issue related to `sqlalchemy` but I'm not sure what's the reason.

Hello, now I got new error:
$ dragonfire 
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/deepconv/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/deepconv/model-pretrainedv2/model.ckpt
Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==1.0.2', 'console_scripts', 'dragonfire')()
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 732, in initiate
    stray_proc.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

I don't know why.

**Comment by mertyildiran** [comment]
@FilatovRA you are most probably **out-of-memory**. Check out [this SO answer](https://stackoverflow.com/a/13329386/2104879).

**Comment by FilatovRA** [comment]
I also tryed docker. And get an error:
sudo docker run dragonfire

Unable to find image 'dragonfire:latest' locally
docker: Error response from daemon: pull access denied for dragonfire, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by FilatovRA** [comment]
`Dragonfire: GOOD NIGHT SIR
________________________________________________________________________________

2019-05-10 22:24:56,634 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-05-10 22:24:56,634 INFO sqlalchemy.engine.base.Engine ()
2019-05-10 22:24:56,636 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-05-10 22:24:56,636 INFO sqlalchemy.engine.base.Engine ()
2019-05-10 22:24:56,637 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("users")
2019-05-10 22:24:56,637 INFO sqlalchemy.engine.base.Engine ()
2019-05-10 22:24:56,638 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("facts")
2019-05-10 22:24:56,639 INFO sqlalchemy.engine.base.Engine ()
2019-05-10 22:24:56,639 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("notifications")
2019-05-10 22:24:56,639 INFO sqlalchemy.engine.base.Engine ()
2019-05-10 22:24:56,639 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("notepad")
2019-05-10 22:24:56,639 INFO sqlalchemy.engine.base.Engine ()
Illegal instruction (core dumped)
`

**Comment by FilatovRA** [comment]
The solution I found by Google is to downgrade Tensorflow. I'll try it/

**Comment by FilatovRA** [comment]
ERROR: dragonfire 1.0.2 has requirement tensorflow==1.0.0, but you'll have tensorflow 1.5.0 which is incompatible.

**Comment by FilatovRA** [comment]
I am pretty shure the problem is in my old PC:
python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
2019-05-11 12:38:05.020708: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.
Aborted (core dumped)

**Comment by mertyildiran** [comment]
@FilatovRA I don't understand what's the issue right now. You post a lot of different outputs that come from different TensorFlow versions. Yes, Dragonfire depends on TensorFlow version `1.0.0`.

[Dockerfile](https://github.com/DragonComputer/Dragonfire/blob/master/Dockerfile) is outdated, so I don't recommend to use that.

**Comment by luntik2012** [comment]
could somebody update it please? cannot use this on archlinux...
