### ISSUE TITLE
ubuntu 18

### ISSUE THREAD

**Issue by genikineg** [DragonComputer/Dragonfire#117]
Dragonfire not work,,

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SQLAlchemy 1.3.3 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('SQLAlchemy==1.2.10'), {'dragonfire'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'SQLAlchemy==1.2.10' distribution was not found and is required by dragonfire

**Comment by genikineg** [comment]
install deb

$ dragonfire
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/deepconv/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/deepconv/model-pretrainedv2/model.ckpt
_____________________________________________________________________________________________________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 80, in __load
    try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 675, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource names not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('names')
  
  Searched in:
    - '/home/pc/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==1.0.2', 'console_scripts', 'dragonfire')()
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 733, in initiate
    greet(userin)
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 675, in greet
    gender = Classifier.gender(user_full_name.split(' ', 1)[0])
  File "/usr/lib/python3/dist-packages/dragonfire/nlplib.py", line 50, in gender
    labeled_names = ([(name, 'male') for name in names.words('male.txt')] +
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 78, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 675, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource names not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('names')
  
  Searched in:
    - '/home/pc/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
**********************************************************************

**Comment by mertyildiran** [comment]
@genikineg because of the latest commit https://github.com/DragonComputer/Dragonfire/commit/4c0e873e0bee3553bf14dfb1dded85e7fa515434 

I'm gonna fix it on the weekend.

**Comment by genikineg** [comment]
I will be very happy if after updating everything will work for me)
