### ISSUE TITLE
 deeppavlov 0.8.0 not supported

### ISSUE THREAD

**Issue by iguanen** [DragonComputer/Dragonfire#142]
ERROR: dragonfire 1.1.1 has requirement deeppavlov==0.7.1, but you'll have deeppavlov 0.8.0 which is incompatible.

How to downgrade to deeppavlov==0.7.1 ?

**Comment by mertyildiran** [comment]
@iguanen you can try to change the version from [here](https://github.com/DragonComputer/Dragonfire/blob/master/requirements.txt#L23). Probably you should set that line to `deeppavlov>=0.7.1` or `deeppavlov==0.8.0`

**Comment by iguanen** [comment]
Did not help, I get this output when trying to start dragonfire

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (deeppavlov 0.8.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('deeppavlov==0.7.1'), {'dragonfire'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'deeppavlov==0.7.1' distribution was not found and is required by dragonfire
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_dragonfire.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (deeppavlov 0.8.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('deeppavlov==0.7.1'), {'dragonfire'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'deeppavlov==0.7.1' distribution was not found and is required by dragonfire

**Comment by mertyildiran** [comment]
@iguanen it's because Dragonfire is already installed with `deeppavlov==0.7.1` dependency. So first run `make pip-uninstall` or `make dev-pip-uninstall` to remove Dragonfire and then run `make install` to reinstall it.
