### ISSUE TITLE
Compatible OS!

### ISSUE THREAD

**Issue by Shadowfire69** [DragonComputer/Dragonfire#146]
First let me say that I'm brand new to Linux and thought that this project was beyond cool but no matter what I do I cant seem to get Dragonfire to work.
I've tried to install this on KDE neon, Kubuntu 20.04, Ubuntu 20.04, and openSUSE and every time I get the same errors:
"No compatible models found for v3.0.0 of spaCy"
"Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ModuleNotFoundError: No module named 'deeppavlov'"
Now at the same time I get these errors once the installation finishes I get the message:
"Dragonfire is successfully installed to your computer."
But every time I try to call Dragonfire from the terminal I get the message:
"        ": command not found.
I have read through all the posts on gitter plus all the "Issues" here to no avail and have already tried to get the version 1.2.0 through git clone but I get the message that the file is not found. At this point I'm at a loss pulling my hair out trying to get this working so can you recommend a fix or a Linux OS that is actually compatible for Dragonfire with preferably a KDE environment?

**Comment by mertyildiran** [comment]
@Shadowfire69 please try `1.2.0` branch: https://github.com/DragonComputer/Dragonfire/tree/1.2.0

**Comment by Shadowfire69** [comment]
I have tried 1.2.0 a few times now but it won't work and I get the error:
"fatal: repository 'https://github.com/DragonComputer/Dragonfire/tree/1.2.0/' not found".

**Comment by mertyildiran** [comment]
@Shadowfire69 it's;

```shell
git clone https://github.com/DragonComputer/Dragonfire.git
cd Dragonfire/
git checkout 1.2.0
```

not;

```shell
git clone https://github.com/DragonComputer/Dragonfire/tree/1.2.0/
```

So you should do branch switching not cloning.

**Comment by Shadowfire69** [comment]
> @Shadowfire69 it's;
> 
> ```shell
> git clone https://github.com/DragonComputer/Dragonfire.git
> cd Dragonfire/
> git checkout 1.2.0
> ```
> 
> not;
> 
> ```shell
> git clone https://github.com/DragonComputer/Dragonfire/tree/1.2.0/
> ```
> 
> So you should do branch switching not cloning.

Thanks! But I'm still getting the same errors as before, so my question becomes what is the best or most compatible Ubuntu(assuming Kubuntu would work just the same)/Python version to use with Dragonfire?

**Comment by mertyildiran** [comment]
@Shadowfire69 latest passing test was https://github.com/DragonComputer/Dragonfire/tree/e9f2dce872c43210062db1e2022097c4b8aa7781 which ran on Ubuntu 18.04 The default Python 3.x (`python3 --version`) on Ubuntu 18.04 is tested hence approved that it's working.

**Comment by Shadowfire69** [comment]
> @Shadowfire69 latest passing test was https://github.com/DragonComputer/Dragonfire/tree/e9f2dce872c43210062db1e2022097c4b8aa7781 which ran on Ubuntu 18.04 The default Python 3.x (`python3 --version`) on Ubuntu 18.04 is tested hence approved that it's working.

OK I don't know what I'm doing wrong because I installed Unbuntu 18.04 which resolved the "spaCy" issue but I'm still getting the deepavlov error:

 ./debian/postinst: line 90: 28349 Illegal instruction     (core dumped) python3 -m spacy download en
/usr/bin/python3: No module named deeppavlov
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ModuleNotFoundError: No module named 'deeppavlov'

I know that deeppavlov is install on my OS because I used pip3 to install it + nltk, deepspeech, tensorflow, spaCy, etc before even trying to install Dragonfire, so I'm not sure why it's still having this problem.

With it telling me Dragonfire is successfully installed from the terminal:
dragonfire: command not found.

I appreciate the time you've taken to help me.

**Comment by mertyildiran** [comment]
@Shadowfire69 if you're sure that you have `deeppavlov` package on your system then try to remove it from the dependencies or change the version criteria on [this line](https://github.com/DragonComputer/Dragonfire/blob/master/requirements.txt#L23). Because it seems like there is a version mismatch.

**Comment by Shadowfire69** [comment]
> @Shadowfire69 if you're sure that you have `deeppavlov` package on your system then try to remove it from the dependencies or change the version criteria on [this line](https://github.com/DragonComputer/Dragonfire/blob/master/requirements.txt#L23). Because it seems like there is a version mismatch.

So I just did a clean install of Ubuntu 18.04 and copied & pasted all 23 of the dependency's names to pip3 install "     " which installed everything normally with no errors or problems but still for some reason I'm getting the same "no module named deeppavlov" error and "dragonfire:command not found" in the terminal.
