### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by EneroPl** [DragonComputer/Dragonfire#157]
I enter command `python3 -m dragonfire -h` or just `dragonfire`, but it's output this module error and I can't fix it. 

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 33, in <module>
    from dragonfire.learn import Learner  # Submodule of Dragonfire that forms her learning ability
  File "/usr/lib/python3/dist-packages/dragonfire/learn.py", line 13, in <module>
    from tinydb import TinyDB, Query  # TinyDB is a lightweight document oriented database
ModuleNotFoundError: No module named 'tinydb'

**Comment by Pranoypauljr** [comment]
try manually installing the tinydb package with the given version in requirements.txt file
run the command -> pip install tinydb==3.9.0.post1   ,in your terminal (within your virtual env if any.)
