### ISSUE TITLE
I can t initialize Dragonfire 

### ISSUE THREAD

**Issue by stef7773** [DragonComputer/Dragonfire#165]
Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'deeppavlov==0.7.1' distribution was not found and is required by dragonfire

**Comment by gungugugungu** [comment]
I'm having the same issue, did you manage to solve this issue? I installed deeppavlov, and it still doesn't work

**Comment by stef7773** [comment]
Hello, no I never could solve the problem. I had a lot of trouble with
python environments versions required to launch Dragonfire and also the
command that run the program was missing so i couldn't also initialize
Dragonfire.
