### ISSUE TITLE
 Warning: no model found for 'en'

### ISSUE THREAD

**Issue by ddeath** [DragonComputer/Dragonfire#28]
When I was trying to run dragonfire I got following warning:

 Warning: no model found for 'en'

And dragonfire ended on exception.

Looks like the solution is:

sudo python -m spacy.en.download all

**Comment by mertyildiran** [comment]
@ddeath actually it's included in [this line](https://github.com/DragonComputer/Dragonfire/blob/master/setup.py#L30) and [this line](https://github.com/DragonComputer/Dragonfire/blob/master/setup.py#L48). Probably something bad happened on the installation before getting to that stage.

Could you please try to install it with **verbose**(-v) option: `sudo pip install -ve .` and tell me what do you see, an error or warning?

**Comment by ddeath** [comment]
During the installation from git code it will stop on this error:

```
Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
        mod_name, _Error)
      File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
        __import__(mod_name)  # Do not catch exceptions initializing package
      File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 8, in <module>
        from . import en, de, zh, es, it, hu, fr, pt, nl, sv, fi, bn, he
    ImportError: cannot import name en
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ddeath/projects/Dragonfire/setup.py", line 199, in <module>
        **pkgconfig('gtk+-2.0 x11 xext')
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ddeath/projects/Dragonfire/setup.py", line 30, in run
        check_call("python -m spacy download en".split())
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['python', '-m', 'spacy', 'download', 'en']' returned non-zero exit status 1
Cleaning up...
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/ddeath/projects/Dragonfire/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/ddeath/projects/Dragonfire/
Exception information:
Traceback (most recent call last):
  File "/home/ddeath/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ddeath/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/ddeath/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/ddeath/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/home/ddeath/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/home/ddeath/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/ddeath/projects/Dragonfire/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/ddeath/projects/Dragonfire/
```

**Comment by cclauss** [comment]
Does this help?  https://stackoverflow.com/questions/43459437/spacy-link-error
