### ISSUE TITLE
Error when invoking dragonfire

### ISSUE THREAD

**Issue by rccclr** [DragonComputer/Dragonfire#30]
Hello,
Please help for this error.
Thanks

(Ubuntu 14.4)

Traceback (most recent call last):
  File "/usr/local/bin/dragonfire", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: youtube-dl

**Comment by mertyildiran** [comment]
@rccclr `pip install youtube_dl` can fix this error.

Maybe I made a mistake when uploading the new version to PyPI. I will check it out...

[**Install Dragonfire in Development Mode**](https://github.com/DragonComputer/Dragonfire/blob/master/CONTRIBUTING.md#install-dragonfire-in-development-mode) can definitely solve all possible problems on your system. We are planning to release a `.deb` with 1.0.0

Unfortunately on PyPI it's not working perfectly. :confused:

**Comment by rccclr** [comment]
Many thanks 
From development mode --> ok
I test with GOOD MORNING, but remain in loop (attach the console log)
Congratulations for the work!!!

You: GOOD MORNING
Dragonfire: SORRY, I DON'T UNDERSTAND THE SUBJECT OF YOUR QUESTION.
_______________________________________________________________

You: SUBJECTIVE
Dragonfire: SORRY, I DON'T UNDERSTAND THE SUBJECT OF YOUR QUESTION.
_______________________________________________________________

You: SUBJECT
Dragonfire: SORRY, I DON'T UNDERSTAND THE SUBJECT OF YOUR QUESTION.
_______________________________________________________________

**Comment by mertyildiran** [comment]
@rccclr there is no built-in command called `GOOD MORNING`.

Dragonfire is confusing with her own voice. Try to listen it with your headphones instead of the speakers.

**Comment by EnforcerZhukov** [comment]
Got this error from Ubuntu 14.04.1

```
rayne@Asus:~/Desktop/dragonfire/Dragonfire-master$ dragonfire
Traceback (most recent call last):
  File "/usr/share/python/dragonfire/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests<2.19,>=2.18.2' distribution was not found and is required by pyowm
```

**Comment by mertyildiran** [comment]
@EnforcerZhukov you should install `pyowm` manually with `pip install pyowm` command.
