### ISSUE TITLE
Dragonfire is not able to start

### ISSUE THREAD

**Issue by evplv** [DragonComputer/Dragonfire#39]
After clean download and install I get following error:
```
Traceback (most recent call last):
  File "/usr/share/python/dragonfire/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), set(['pyasn1-modules']))
```

**Comment by mertyildiran** [comment]
@evplv could you please try to run `apt-get install python-pyasn1` or `pip install pyasn1 --upgrade` then try to run `dragonfire` again and tell me if it works or not? :blush: 

By the way, what distro is that? This is the first time I saw that error. Please tell me with the version number like Ubuntu 16.04.

**Comment by huayra** [comment]
Same problem, but different message (had dependency issues getting to install the deb file). Im running 16.04 and it does simply not work.

$ dragonfire 
Traceback (most recent call last):
  File "/usr/share/python/dragonfire/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==0.9.6', 'console_scripts', 'dragonfire')()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/__init__.py", line 8, in <module>
    from dragonfire.nlplib import Classifiers
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/nlplib.py", line 28, in <module>
    brown_train = brown.tagged_sents(categories='news')
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource brown not found.

**Comment by mertyildiran** [comment]
@huayra I think you interrupted the installation at some point. It should have install NTLK's Brown corpus with [this line](https://github.com/DragonComputer/Dragonfire/blob/master/debian/postinst#L36). Please try to reinstall Dragonfire or try to run `printf "import nltk\nnltk.download('names')\nnltk.download('brown')\nnltk.download('wordnet')" | python` as the last resort. (but running this command will not fix any other missing dependencies rather than NTLK corpuses)

**Comment by huayra** [comment]
@mertyildiran you are right. I even had to install nnltk manually, beføre I got the brown error. I saw issues outside of pip installed dependencies, as the installation generates A LOT of dependency issues even in Debian, which I corrected by manually installing every single dependency and using aptitude to try and solve any issues that arised (i.e. Skype and other software had to go).

In the end dragonfire did not work and I do not normally have a lot of time to test (installing it takes a while). I'll await a new release or a new .deb file before I attempt using it again.

**Comment by evplv** [comment]
@mertyildiran sorry for the delayed answer.
when I install pyasn1 with apt I get the following trace:
```
  File "/usr/share/python/dragonfire/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), set(['pyasn1-modules']))
```
When I install remove it with apt and install it with pip:
```
  File "/usr/share/python/dragonfire/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==0.9.6', 'console_scripts', 'dragonfire')()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/__init__.py", line 9, in <module>
    from dragonfire.omniscient import Engine
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/omniscient.py", line 1, in <module>
    import wikipedia # Provides and API-like functionality to search and access Wikipedia data
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/__init__.py", line 1, in <module>
    from .wikipedia import *
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

**Comment by mertyildiran** [comment]
@evplv these are errors that are coming from too deep (in package-wise) so I don't even understand the situation. Please wait for the new release. (coming in a few days)

**Comment by mertyildiran** [comment]
@evplv and @huayra all of these problems are fixed in the [latest release](https://github.com/DragonComputer/Dragonfire/releases/tag/v0.9.7) of Dragonfire.

Feel free to open this issue again if you encounter with similar problems. :blush:
