### ISSUE TITLE
install issue on linux mint

### ISSUE THREAD

**Issue by stewiemo** [DragonComputer/Dragonfire#66]
i have ran all install steps and troubleshoot for the dependancies but still get this issue

user@stewiemo ~/Dragonfire $ dragonfire
Traceback (most recent call last):
  File "/usr/share/python/dragonfire/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyowm' distribution was not found and is required by dragonfire
user@stewiemo ~/Dragonfire $ 

any fix?

**Comment by wrapperband** [comment]
I am getting the same issue with Kubuntu 17.10, I also have re installed, and tried apt installing the dependencies.

**Comment by mertyildiran** [comment]
@stewiemo and @wrapperband you can install **pyowm** manually with `pip install pyowm`

[For more information about PyOWM](https://github.com/csparpa/pyowm#pyowm-sunny-umbrella-snake)
