### ISSUE TITLE
realhud C extension causing problem for Python 3 compatibility

### ISSUE THREAD

**Issue by mertyildiran** [DragonComputer/Dragonfire#70]
When I try to install Dragonfire for Python 3 with `pip3 install -e .` command; [these lines](https://github.com/DragonComputer/Dragonfire/blob/master/setup.py#L153-L154) causing an error:

```Shell
Obtaining file:///home/mertyildiran/Documents/Dragonfire
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mertyildiran/Documents/Dragonfire/setup.py", line 154, in <module>
        **pkgconfig('gtk+-2.0 x11 xext'))
      File "/home/mertyildiran/Documents/Dragonfire/setup.py", line 37, in pkgconfig
        config.setdefault(flags[flag], []).append(value)
    KeyError: b'-p'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/mertyildiran/Documents/Dragonfire/

```

**Comment by mertyildiran** [comment]
Fixed with https://github.com/DragonComputer/Dragonfire/commit/1c16ce76a58a722cc75dde915b5953e0aa32918a
