### ISSUE TITLE
Not working on kubuntu

### ISSUE THREAD

**Issue by syhgorath** [DragonComputer/Dragonfire#75]
i couldnt use it on pardus thats why i install kubuntu and i could install with no error but when i try to run it gives the error below;
Traceback (most recent call last):
  File "/usr/local/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==0.9.9', 'console_scripts', 'dragonfire')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/dragonfire/__init__.py", line 45, in <module>
    from dragonfire.conversational import DeepConversation
  File "/usr/local/lib/python3.6/dist-packages/dragonfire/conversational/__init__.py", line 14, in <module>
    from dragonfire.conversational.textdata import TextData
  File "/usr/local/lib/python3.6/dist-packages/dragonfire/conversational/textdata.py", line 15, in <module>
    from dragonfire.conversational.corpus.cornelldata import CornellData
ModuleNotFoundError: No module named 'dragonfire.conversational.corpus'
i try to search for it but i couldnt do :(

**Comment by mertyildiran** [comment]
@syhgorath Have you ever tried to install Dragonfire using [install.sh](https://github.com/DragonComputer/Dragonfire/blob/master/install.sh) script? Just run: `sudo ./install.sh`

**Comment by syhgorath** [comment]
Yes i did.

**Comment by KrVignesh** [comment]
I had same issue as your's and i solved using  (https://github.com/DragonComputer/Dragonfire/issues/73)

Just edit your setup.py at [Line 94](https://github.com/DragonComputer/Dragonfire/blob/master/setup.py#L94) to whatever python version you are using
If you are using python 3.6 change
`'Programming Language :: Python :: 3 :: Only',`
to
`'Programming Language :: Python :: 3.6 :: Only',`

and manually copy `corpus` folder from 
`Dragonfire/dragonfire/conversational/` 
to 
`/usr/local/lib/python3.6/dist-packages/dragonfire/conversational/`

finally run `sudo ./install.sh`

**Comment by mertyildiran** [comment]
@KrVignesh could you find a version independent solution (like; both works for Python 3.5 and Python 3.6) and send a pull request?

**Comment by mertyildiran** [comment]
@syhgorath fixed with https://github.com/DragonComputer/Dragonfire/commit/6f5d0881c27803a9920cba886bae8f07a7b83cce
