### ISSUE TITLE
Finally it not working under Debian 9.

### ISSUE THREAD

**Issue by turtle-bazon** [DragonComputer/Dragonfire#77]
After resolving issue #76 it seems start. But it seems not working according https://www.youtube.com/watch?v=krHUzY2DylI. No reaction on voice and no hello from program. My dragonfire output:
```
turtle@working-turtle /tmp $ dragonfire
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/conversational/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/conversational/model-pretrainedv2/model.ckpt
_______________________________________________________________


** (dragonfire:16494): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(dragonfire:16494): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(dragonfire:16494): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(dragonfire:16494): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==1.0.0', 'console_scripts', 'dragonfire')()
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 635, in initiate
    dragon_greet()
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 574, in dragon_greet
    gender = Classifier.gender(user_full_name.split(' ', 1)[0])
  File "/usr/lib/python3/dist-packages/dragonfire/nlplib.py", line 26, in gender
    return classifier.classify(Classifier.gender_features(word))
  File "/usr/lib/python3/dist-packages/dragonfire/nlplib.py", line 14, in gender_features
    return {'last_letter': word[-1]}
IndexError: string index out of range
```

**Comment by turtle-bazon** [comment]
Again, it doesn't start under user without executing ```printf "import nltk\nnltk.download('names')\nnltk.download('brown')\nnltk.download('wordnet')\nnltk.download('punkt')" | python3```

**Comment by mertyildiran** [comment]
@turtle-bazon I don't understand. Is running `printf "import nltk\nnltk.download('names')\nnltk.download('brown')\nnltk.download('wordnet')\nnltk.download('punkt')" | python3` fixed the issue?

**Comment by turtle-bazon** [comment]
No, downloading nltk resources fixed one issue. That log after this fix i.e. it starts, but not working. I can see icon in systray but it doesn't say anything and not respond to my voice.

**Comment by mertyildiran** [comment]
@turtle-bazon [this block](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/nlplib.py#L11-L26) determines your gender based on the full name that you have given on the installation of your linux.

What is your full name may I ask?
```
command = "getent passwd $LOGNAME | cut -d: -f5 | cut -d, -f1"
user_full_name = os.popen(command).read()
user_full_name = user_full_name[:-1] 
```

Is it empty or something like that? Is the last letter of your full name is a blank character? Is there a weird character? There is something wrong with your full name that recorded in the operating system.

**Comment by turtle-bazon** [comment]
Yes, it is empty:
```
turtle@working-turtle ~ $ getent passwd turtle | cut -d: -f5 | cut -d, -f1|hexdump -C
00000000  0a                                                |.|
00000001
```

**Comment by mertyildiran** [comment]
@turtle-bazon so that's the reason of `IndexError: string index out of range`. We should handle such a possibility. So could you add a few lines like:

```
if word is empty:
    return a as last_letter
else:
    return word[-1] as the last_letter
```

to [here](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/nlplib.py#L14) and **send a pull request**?

By the way please don't ask me why there is this method there because I don't even remember the actual reason. 😆

**Comment by turtle-bazon** [comment]
Ok, this solved that issue, but it not working anyway. :) I hear "Good evening, my lady", but then no reaction on any commands.

```
turtle@working-turtle ~ $ dragonfire                                                                                                                                                      
TensorFlow detected: v1.0.0                                                                                                                                                                 
                                                                                                                                                                                            
Warning: Restoring parameters:                                                                                                                                                              
globStep: 32000                                                                                                                                                                             
watsonMode: False                                                                                                                                                                           
autoEncode: False                                                                                                                                                                           
corpus: cornell                                                                                                                                                                             
datasetTag: old                                                                                                                                                                             
maxLength: 10                                                                                                                                                                               
filterVocab: 0                                                                                                                                                                              
skipLines: False                                                                                                                                                                            
vocabularySize: 0                                                                                                                                                                           
hiddenSize: 512                                                                                                                                                                             
numLayers: 2                                                                                                                                                                                
softmaxSamples: 0                                                                                                                                                                           
initEmbeddings: False                                                                                                                                                                       
embeddingSize: 64                                                                                                                                                                           
embeddingSource: None                                                                                                                                                                       
                                                                                                                                                                                            
Loading dataset from /usr/share/dragonfire/conversational/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA                
Model creation...                                                        
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computa$
ions.                                                           
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU compu$
ations.                                                                    
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU compu$
ations.        
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computat$
ons.                                        
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computat$
ons.                                                              
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/conversational/model-pretrainedv2/model.ckpt
_______________________________________________________________

                                     
** (dragonfire:18295): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
                                                                    
(dragonfire:18295): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed i$
 a future version                                                                          

(dragonfire:18295): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in
 a future version

(dragonfire:18295): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be
 removed in a future version
Dragonfire: GOOD EVENING MY LADY
_______________________________________________________________

TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.5-0-g7cc8382
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-06-27 19:08:40.537109: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

**Comment by mertyildiran** [comment]
@turtle-bazon first of all try to run with `--cli` option like this: `dragonfire --cli` to see if she is working correctly. Because without `--cli` option she takes voice inputs and something can be wrong with speech recognition.

If there is a problem with speech recognition then please create a new issue.

I assume that this issue is fixed with https://github.com/DragonComputer/Dragonfire/commit/4dacdee5409726c2dc3b3af8c4d6f5b7e3b870ef
