### ISSUE TITLE
Cannot activate using voice in Ubuntu 16.04

### ISSUE THREAD

**Issue by rpuch** [DragonComputer/Dragonfire#80]
I've just installed Dragonfire using `sudo dpkg -i dragonfire_1.0.0_amd64.deb` on my Ubuntu 16.04. My system has a microphone and it works in Chrome, for example.

I run Dragonfire in a terminal using `dragonfire` command. Here is what I see:

```
$ dragonfire 
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/conversational/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/conversational/model-pretrainedv2/model.ckpt
_______________________________________________________________

Dragonfire: GOOD AFTERNOON MY LADY
_______________________________________________________________

TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.5-0-g7cc8382
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-06-24 15:18:04.384803: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

Then I said for a few times 'Dragonfire' and 'Wake up'. Nothing happened. A bit later, a few new lines appeared in the terminal window:

```
You: NO 
You: YET 
You: IT 
You: TOM
You: TOM 
You: SO 
You: PAUL 
You: WOW
You: OH 
You: NO 
```

It looks like it 'recognizes' something, but this is just some garbage.

The speech recognition is clearly not working. How can I debug it to find the culprit?

**Comment by mertyildiran** [comment]
@rpuch please try to run Dragonfire with `dragonfire --gspeech` option so she will use Google Speech Recognition Service to understand your voice command. Default speech recognition method is Mozilla DeepSpeech which has high [WER](https://en.wikipedia.org/wiki/Word_error_rate).

**Comment by rpuch** [comment]
Thank you for the suggestion, but the only difference with `--gspeech` is that now Dragonfire does not recognize anything at all, even that noise. Instead, later, 1-2 minutes after I tried to pronounce these 'Dragonfire' and 'Wake up', I got an error:

```
Dragonfire: GOOD EVENING MY LADY
_______________________________________________________________

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==1.0.0', 'console_scripts', 'dragonfire')()
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 636, in initiate
    start(args)
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 103, in start
    recognizer.recognize(args)
  File "/usr/lib/python3/dist-packages/dragonfire/sr/gspeech.py", line 72, in recognize
    com = self.recognizer.recognize_google(audio_data)
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 840, in recognize_google
    response = urlopen(request, timeout=self.operation_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Are those 'Cannot connect to server' lines normal?

**Comment by mertyildiran** [comment]
@rpuch `Cannot connect to server` warning is actually related to system tray icon and nothing to do with speech recognition.

You should search for `ConnectionResetError: [Errno 104] Connection reset by peer` in [here](https://github.com/Uberi/speech_recognition) because it comes from that package.
