### ISSUE TITLE
crash when running docker image

### ISSUE THREAD

**Issue by magick93** [DragonComputer/Dragonfire#89]
Hello

I tried to run `docker run dragoncomputer/dragonfire -s` , but it resulted in a crash - see output below.

Im running on Ubuntu 18.04, 16gm ram, i7 cpu.

```
docker run dragoncomputer/dragonfire -s
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/conversational/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/conversational/model-pretrainedv2/model.ckpt
_______________________________________________________________

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dragonfire/stray.py", line 58, in SystemTrayInit
    SystemTrayIcon()
  File "/usr/local/lib/python3.5/dist-packages/dragonfire/stray.py", line 15, in __init__
    import gi
ImportError: No module named 'gi'
Dragonfire: GOOD MORNING SIR
_______________________________________________________________

TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.5-0-g7cc8382
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-09-01 05:09:18.675563: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: /usr/share/dragonfire/deepspeech/models/output_graph.pb; No such file or directory
terminate called after throwing an instance of 'util::ErrnoException'
  what():  native_client/kenlm/util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'.
No such file or directory while opening /usr/share/dragonfire/deepspeech/models/lm.binary

```

**Comment by lebedov** [comment]
It would be desirable to clarify that the Docker image is only intended for server-side use in the project README.

**Comment by mertyildiran** [comment]
@lebedov correct, feel free to update `README.md` and send a PR(since you proposed the change).

**Comment by lebedov** [comment]
PR submitted.

**Comment by stef7773** [comment]
Hello I installed Dragonfire but i can t run it. Which is the command to run it please ?
