### ISSUE TITLE
Can't connect to MySQL server on 'MYSQL_HOST' ([Errno -2] Name or service not known)")

### ISSUE THREAD

**Issue by ZhukovGreen** [DragonComputer/Dragonfire#90]
Hi, dragonfire runs and says "Good afternoon, sir", but then the next erro poped

```
File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1005, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'MYSQL_HOST' ([Errno -2] Name or service not known)") (Background on this error at: http://sqlalche.me/e/e3q8)
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
```

**Comment by mertyildiran** [comment]
@ZhukovGreen you should enter the MySQL credentials in [here](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/config.py#L35-L38) if you want to run Dragonfire on server mode.
