### ISSUE TITLE
Dragonfire 1.0.0 / ModuleNotFound "realhud"

### ISSUE THREAD

**Issue by ViralDragon** [DragonComputer/Dragonfire#92]
Hi there. 

I'm running Ubuntu 18.04 using Python3(.6) When attempting to install Dragonfire, I ran into a couple issues which I was able to solve on my own by installing all the dependencies manually. After getting it installed using ./install.sh it comes back dragonfire has been installed successfully. When running dragonfire with "dragonfire", it comes back with a crash that appears to be because of no module named realhud. I tried to install this manually, but I'm unable to find a download for the package or where to even get it. 

I attempted to run it in --headless mode as well, but the same issue. 

viral@Viral:/Desktop/Dragonfire-1.0.0$ dragonfire

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==1.0.0', 'console_scripts', 'dragonfire')()
  File "/home/viral/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/viral/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/viral/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/viral/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 43, in <module>
    from dragonfire.utilities import TTA
  File "/usr/lib/python3/dist-packages/dragonfire/utilities.py", line 14, in <module>
    import realhud
ModuleNotFoundError: No module named 'realhud'

viral@Viral:/Desktop/Dragonfire-1.0.0$ 
----------------------

Running "sudo dpkg -i dragonfire_1.0.0_amd64.deb", just tells me it requires python3.6 but says I have 3.6.5 installed. After doing some looking around someone had the same issue and I used that to help solve the issue, ended up just using ./install.sh anyway to install it. I wasn't able to find a crash report though anywhere. 

Edit: Apologies for the weird formatting, I didn't realize it was going to jack it with all the underlines. 

Any help would be appreciated.

**Comment by mertyildiran** [comment]
@ViralDragon realhud is [this C program](https://github.com/DragonComputer/Dragonfire/blob/1d8635386ceadd74478ec5c1daf73959494d6b80/dragonfire/realhud/realhud.c) to show the female head animation. Normally **setup.py** should have compile and install that on your system but I did not understand what's happening on your end.

If you don't need realhud then as a workaround; you can remove all the imports of realhud and the calls in the source and reinstall it:
https://github.com/DragonComputer/Dragonfire/search?q=realhud&unscoped_q=realhud

**Comment by ViralDragon** [comment]
Alright after playing around with it for a bit, I got the errors fixed on my side after re-running builds and install.

However, now when I type in "dragonfire" to activate it, it does the _initial_ wake up process and then that's it. I can say/yell wake up or dragonfire multiple times and nothing happens. It does this both with --gspeech and the default setting. It says "Good afternoon sir", (the head displays, which is pretty cool - though, because I have split monitors, it doesn't display on just one, it does it on both) and then it just stops responding for some reason and I can't force it to wake up and talk to me. 

Here's the console output. 

viral@Viral:~/Desktop/Dragonfire-1.0.0$ dragonfire --gspeech
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/conversational/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/conversational/model-pretrainedv2/model.ckpt
_______________________________________________________________

Dragonfire: GOOD AFTERNOON SIR
_______________________________________________________________

**Comment by ViralDragon** [comment]
Ok, so after making sure that all the audio libraries were installed, I went ahead and rebooted. 
Everything ... is sort of working. So now she'll respond to my voice/commands, but only after I tap on my mic once or twice, which ... makes no sense to me, but hey I'm willing to roll with it. Lollll. 

Other than having to tap on it, she just needs to be trained up some more it looks like so I can hold a decent conversation with her.

**Comment by mertyildiran** [comment]
@ViralDragon there is a volume threshold to trigger the audio recording so either increase the volume of your mic or bring the mic a little bit more closer to your mouth.
